[build]
  publish = "public"
  command = "yarn build"

# Redirect /index.html to /
[[redirects]]
from = "/index.html"
to = "/"
status = 301
force = true

# Redirect any /something/index.html to /something/
[[redirects]]
from = "/:splat/index.html"
to = "/:splat/"
status = 301
force = true

# (optional) canonical host, if you donâ€™t want www
[[redirects]]
from = "http://studio46.co.nz/*"
to = "https://studio46.co.nz/:splat"
status = 301
force = true

[[redirects]]
from = "http://www.studio46.co.nz/*"
to = "https://studio46.co.nz/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.studio46.co.nz/*"
to = "https://studio46.co.nz/:splat"
status = 301
force = true